create table users_data (
	applicant_id INT AUTO_INCREMENT PRIMARY KEY,
	first_name VARCHAR(50),
	last_name VARCHAR(50),
  age INT,
	gender VARCHAR(50),
	email VARCHAR(50),
	address VARCHAR(250),
	job_title VARCHAR(50),
	nationality VARCHAR(50),
	date_added TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
insert into users_data (applicant_id, first_name, last_name, age, gender, email, address, job_title, nationality, date_added) values (1, 'Bernardina', 'Adamski', 23, 'Female', 'badamski0@google.ru', '7 Oakridge Place', 'Construction Expeditor', 'China', '2003-03-28 04:57:22');
insert into users_data (applicant_id, first_name, last_name, age, gender, email, address, job_title, nationality, date_added) values (2, 'Mack', 'Gjerde', 51, 'Male', 'mgjerde1@vimeo.com', '125 Rieder Hill', 'Construction Foreman', 'Kazakhstan', '2006-01-17 17:59:15');
insert into users_data (applicant_id, first_name, last_name, age, gender, email, address, job_title, nationality, date_added) values (3, 'Marleen', 'Brimming', 50, 'Female', 'mbrimming2@ebay.com', '51020 Quincy Street', 'Project Manager', 'Brazil', '2016-09-13 07:54:12');
insert into users_data (applicant_id, first_name, last_name, age, gender, email, address, job_title, nationality, date_added) values (4, 'Benedict', 'Nolli', 23, 'Male', 'bnolli3@google.ru', '5222 Petterle Park', 'Estimator', 'Portugal', '2001-07-25 22:26:31');
insert into users_data (applicant_id, first_name, last_name, age, gender, email, address, job_title, nationality, date_added) values (5, 'Gib', 'Bricham', 61, 'Male', 'gbricham4@hao123.com', '23 Spenser Terrace', 'Construction Foreman', 'Brazil', '2007-11-19 02:38:28');
insert into users_data (applicant_id, first_name, last_name, age, gender, email, address, job_title, nationality, date_added) values (6, 'Nealson', 'Vaudin', 61, 'Male', 'nvaudin5@theatlantic.com', '965 Hagan Hill', 'Estimator', 'Indonesia', '2002-06-22 20:00:29');
insert into users_data (applicant_id, first_name, last_name, age, gender, email, address, job_title, nationality, date_added) values (7, 'Jonah', 'Climance', 62, 'Male', 'jclimance6@ft.com', '40977 Maple Avenue', 'Electrician', 'Guatemala', '2010-03-19 07:17:23');
insert into users_data (applicant_id, first_name, last_name, age, gender, email, address, job_title, nationality, date_added) values (8, 'Edi', 'Blade', 60, 'Female', 'eblade7@histats.com', '9227 Grayhawk Alley', 'Construction Manager', 'Philippines', '2001-01-01 13:01:47');
insert into users_data (applicant_id, first_name, last_name, age, gender, email, address, job_title, nationality, date_added) values (9, 'Amity', 'Moston', 39, 'Female', 'amoston8@ftc.gov', '34521 Randy Road', 'Construction Foreman', 'Bosnia and Herzegovina', '2014-06-30 04:26:07');
insert into users_data (applicant_id, first_name, last_name, age, gender, email, address, job_title, nationality, date_added) values (10, 'Mauricio', 'Cawkill', 59, 'Male', 'mcawkill9@google.co.uk', '1246 Summerview Center', 'Architect', 'China', '2018-12-06 08:54:39');
insert into users_data (applicant_id, first_name, last_name, age, gender, email, address, job_title, nationality, date_added) values (11, 'Bronnie', 'Jillitt', 48, 'Male', 'bjillitta@jugem.jp', '31487 Sachs Way', 'Construction Worker', 'United States', '2007-06-01 17:40:31');
insert into users_data (applicant_id, first_name, last_name, age, gender, email, address, job_title, nationality, date_added) values (12, 'Miles', 'Kahane', 35, 'Male', 'mkahaneb@patch.com', '729 Emmet Trail', 'Supervisor', 'Russia', '2005-12-07 13:01:37');
insert into users_data (applicant_id, first_name, last_name, age, gender, email, address, job_title, nationality, date_added) values (13, 'Tobias', 'Robathon', 57, 'Male', 'trobathonc@last.fm', '893 American Ash Crossing', 'Supervisor', 'China', '2001-11-03 10:40:10');
insert into users_data (applicant_id, first_name, last_name, age, gender, email, address, job_title, nationality, date_added) values (14, 'Vi', 'Brumfitt', 46, 'Female', 'vbrumfittd@wikipedia.org', '420 Manufacturers Avenue', 'Construction Foreman', 'China', '2000-06-21 01:55:32');
insert into users_data (applicant_id, first_name, last_name, age, gender, email, address, job_title, nationality, date_added) values (15, 'Lisa', 'Neasham', 38, 'Female', 'lneashame@wikia.com', '2 Dorton Pass', 'Construction Worker', 'Philippines', '2010-09-21 05:11:08');
insert into users_data (applicant_id, first_name, last_name, age, gender, email, address, job_title, nationality, date_added) values (16, 'Lemmie', 'Macconachy', 57, 'Genderfluid', 'lmacconachyf@about.me', '0469 Walton Center', 'Construction Manager', 'Afghanistan', '2001-07-17 11:26:12');
insert into users_data (applicant_id, first_name, last_name, age, gender, email, address, job_title, nationality, date_added) values (17, 'Joby', 'Deware', 58, 'Female', 'jdewareg@gmpg.org', '74059 Cody Road', 'Surveyor', 'Madagascar', '2009-12-30 16:00:15');
insert into users_data (applicant_id, first_name, last_name, age, gender, email, address, job_title, nationality, date_added) values (18, 'Jillayne', 'Bedding', 27, 'Female', 'jbeddingh@squarespace.com', '87191 Sutteridge Circle', 'Construction Manager', 'Chile', '2020-12-20 05:10:04');
insert into users_data (applicant_id, first_name, last_name, age, gender, email, address, job_title, nationality, date_added) values (19, 'Webb', 'Macauley', 32, 'Male', 'wmacauleyi@geocities.jp', '72453 5th Avenue', 'Engineer', 'Syria', '2008-12-17 23:08:56');
insert into users_data (applicant_id, first_name, last_name, age, gender, email, address, job_title, nationality, date_added) values (20, 'Shana', 'Milne', 31, 'Female', 'smilnej@kickstarter.com', '65153 Bobwhite Place', 'Supervisor', 'Philippines', '2021-09-22 07:52:17');
insert into users_data (applicant_id, first_name, last_name, age, gender, email, address, job_title, nationality, date_added) values (21, 'Mellicent', 'Massimo', 29, 'Female', 'mmassimok@lycos.com', '2865 Kedzie Center', 'Supervisor', 'Thailand', '2010-05-08 01:52:20');
insert into users_data (applicant_id, first_name, last_name, age, gender, email, address, job_title, nationality, date_added) values (22, 'Wakefield', 'Wiggett', 47, 'Male', 'wwiggettl@fda.gov', '2150 Montana Drive', 'Supervisor', 'United States', '2006-03-17 02:19:54');
insert into users_data (applicant_id, first_name, last_name, age, gender, email, address, job_title, nationality, date_added) values (23, 'Dimitri', 'Suttling', 48, 'Male', 'dsuttlingm@sitemeter.com', '97 Onsgard Hill', 'Supervisor', 'China', '2012-08-05 00:53:27');
insert into users_data (applicant_id, first_name, last_name, age, gender, email, address, job_title, nationality, date_added) values (24, 'Grantley', 'Brownlea', 20, 'Male', 'gbrownlean@furl.net', '66 Daystar Junction', 'Subcontractor', 'China', '2010-10-21 23:00:57');
insert into users_data (applicant_id, first_name, last_name, age, gender, email, address, job_title, nationality, date_added) values (25, 'Nikolos', 'Sandifer', 26, 'Non-binary', 'nsandifero@blogtalkradio.com', '86835 Golf View Place', 'Supervisor', 'China', '2016-03-27 23:58:46');
insert into users_data (applicant_id, first_name, last_name, age, gender, email, address, job_title, nationality, date_added) values (26, 'Diane-marie', 'Prium', 63, 'Female', 'dpriump@amazon.co.jp', '232 Corben Crossing', 'Supervisor', 'Uganda', '2000-11-15 16:54:35');
insert into users_data (applicant_id, first_name, last_name, age, gender, email, address, job_title, nationality, date_added) values (27, 'Laurena', 'Kruschev', 25, 'Female', 'lkruschevq@booking.com', '0 Bonner Road', 'Construction Manager', 'France', '2018-06-23 20:51:49');
insert into users_data (applicant_id, first_name, last_name, age, gender, email, address, job_title, nationality, date_added) values (28, 'Revkah', 'Filipychev', 33, 'Female', 'rfilipychevr@statcounter.com', '5 Elmside Park', 'Project Manager', 'Nicaragua', '2003-08-16 01:19:57');
insert into users_data (applicant_id, first_name, last_name, age, gender, email, address, job_title, nationality, date_added) values (29, 'Jennee', 'Champniss', 22, 'Female', 'jchampnisss@list-manage.com', '065 Eggendart Parkway', 'Supervisor', 'Russia', '2014-04-19 16:47:52');
insert into users_data (applicant_id, first_name, last_name, age, gender, email, address, job_title, nationality, date_added) values (30, 'Read', 'Quogan', 36, 'Male', 'rquogant@eventbrite.com', '99081 Mockingbird Lane', 'Project Manager', 'Brazil', '2001-08-21 01:57:26');
insert into users_data (applicant_id, first_name, last_name, age, gender, email, address, job_title, nationality, date_added) values (31, 'Claude', 'Story', 34, 'Female', 'cstoryu@simplemachines.org', '856 Fieldstone Place', 'Architect', 'Armenia', '2017-09-10 23:31:58');
insert into users_data (applicant_id, first_name, last_name, age, gender, email, address, job_title, nationality, date_added) values (32, 'Neilla', 'Ullrich', 47, 'Female', 'nullrichv@tiny.cc', '80 Merry Way', 'Construction Worker', 'Thailand', '2009-03-17 19:19:14');
insert into users_data (applicant_id, first_name, last_name, age, gender, email, address, job_title, nationality, date_added) values (33, 'Phebe', 'Figgs', 20, 'Female', 'pfiggsw@1und1.de', '4174 Superior Way', 'Construction Manager', 'Finland', '2005-04-06 14:42:39');
insert into users_data (applicant_id, first_name, last_name, age, gender, email, address, job_title, nationality, date_added) values (34, 'Corbet', 'Gosnell', 58, 'Male', 'cgosnellx@behance.net', '16820 Eagle Crest Trail', 'Construction Worker', 'Australia', '2022-05-21 03:34:34');
insert into users_data (applicant_id, first_name, last_name, age, gender, email, address, job_title, nationality, date_added) values (35, 'Jodi', 'Caven', 49, 'Male', 'jcaveny@soundcloud.com', '36 Birchwood Hill', 'Construction Worker', 'China', '2005-04-13 14:25:23');
insert into users_data (applicant_id, first_name, last_name, age, gender, email, address, job_title, nationality, date_added) values (36, 'Donica', 'Croston', 36, 'Female', 'dcrostonz@barnesandnoble.com', '43167 Stang Drive', 'Engineer', 'Indonesia', '2009-10-31 21:41:52');
insert into users_data (applicant_id, first_name, last_name, age, gender, email, address, job_title, nationality, date_added) values (37, 'Reinhard', 'Snelson', 51, 'Male', 'rsnelson10@live.com', '7382 Dovetail Pass', 'Surveyor', 'China', '2005-07-04 15:23:18');
insert into users_data (applicant_id, first_name, last_name, age, gender, email, address, job_title, nationality, date_added) values (38, 'Irvin', 'Twinberrow', 21, 'Male', 'itwinberrow11@bandcamp.com', '98537 Jay Street', 'Project Manager', 'Pakistan', '2022-12-13 15:31:44');
insert into users_data (applicant_id, first_name, last_name, age, gender, email, address, job_title, nationality, date_added) values (39, 'Nathanil', 'McCurley', 30, 'Male', 'nmccurley12@alibaba.com', '13330 Merchant Center', 'Surveyor', 'Brazil', '2011-04-26 06:53:22');
insert into users_data (applicant_id, first_name, last_name, age, gender, email, address, job_title, nationality, date_added) values (40, 'Camel', 'Jeremiah', 44, 'Female', 'cjeremiah13@dmoz.org', '833 Maple Wood Park', 'Supervisor', 'Georgia', '2007-08-09 07:54:24');
insert into users_data (applicant_id, first_name, last_name, age, gender, email, address, job_title, nationality, date_added) values (41, 'Erl', 'Woolmer', 55, 'Male', 'ewoolmer14@dagondesign.com', '5747 Elmside Terrace', 'Subcontractor', 'Myanmar', '2013-05-11 16:19:36');
insert into users_data (applicant_id, first_name, last_name, age, gender, email, address, job_title, nationality, date_added) values (42, 'Antonius', 'Whetnall', 26, 'Male', 'awhetnall15@timesonline.co.uk', '051 Monica Hill', 'Construction Worker', 'France', '2006-11-07 16:45:53');
insert into users_data (applicant_id, first_name, last_name, age, gender, email, address, job_title, nationality, date_added) values (43, 'Janelle', 'Allmann', 47, 'Female', 'jallmann16@bandcamp.com', '9574 Westend Avenue', 'Electrician', 'Japan', '2022-10-09 19:33:56');
insert into users_data (applicant_id, first_name, last_name, age, gender, email, address, job_title, nationality, date_added) values (44, 'Derron', 'McKaile', 58, 'Male', 'dmckaile17@ovh.net', '38827 Marquette Hill', 'Construction Foreman', 'Malaysia', '2016-12-22 15:47:15');
insert into users_data (applicant_id, first_name, last_name, age, gender, email, address, job_title, nationality, date_added) values (45, 'Nikaniki', 'Maunton', 51, 'Female', 'nmaunton18@free.fr', '573 Colorado Drive', 'Surveyor', 'Kazakhstan', '2016-03-09 18:11:27');
insert into users_data (applicant_id, first_name, last_name, age, gender, email, address, job_title, nationality, date_added) values (46, 'Xerxes', 'MacNockater', 24, 'Agender', 'xmacnockater19@loc.gov', '35290 Morningstar Street', 'Surveyor', 'Indonesia', '2018-01-24 20:08:08');
insert into users_data (applicant_id, first_name, last_name, age, gender, email, address, job_title, nationality, date_added) values (47, 'Desiree', 'Stell', 64, 'Female', 'dstell1a@themeforest.net', '90 Porter Crossing', 'Surveyor', 'China', '2001-01-14 15:52:33');
insert into users_data (applicant_id, first_name, last_name, age, gender, email, address, job_title, nationality, date_added) values (48, 'Else', 'Seagood', 59, 'Female', 'eseagood1b@weibo.com', '10861 Clove Point', 'Construction Foreman', 'Portugal', '2010-12-30 22:13:22');
insert into users_data (applicant_id, first_name, last_name, age, gender, email, address, job_title, nationality, date_added) values (49, 'Caspar', 'Androck', 54, 'Male', 'candrock1c@mtv.com', '134 Heffernan Court', 'Engineer', 'China', '2013-03-03 09:33:13');
insert into users_data (applicant_id, first_name, last_name, age, gender, email, address, job_title, nationality, date_added) values (50, 'Onfroi', 'Heckney', 43, 'Male', 'oheckney1d@foxnews.com', '5314 Northview Way', 'Construction Expeditor', 'Canada', '2010-07-21 10:40:40');